### ISSUE TITLE
[feat] : 메인페이지 UI 구현완료

### ISSUE THREAD

**Issue by senterFoward** [Outfit-of-the-Trip/OOTT-APP#4]
메인 페이지 UI 구현 완료했습니다. 하지만, 현재 UI가 좀 빈약하고 기능부분이 아직 완성되어있지 않아서 빠른 시일 내에 구현 완료 할 예정입니다. MainScreen 디렉터리 내부에있는 /Recomend 디렉터리는 더보기 기능을 구현하기 위한 페이지입니다. 마지막으로 /src/assts/images로 바텀탭에 있는 아이콘들을 저장 및 구조변경하였습니다.

**Comment by aest3ra** [comment]
넵 확인했습니다!
