### ISSUE TITLE
[feat] MainPage UI,UX 수정

### ISSUE THREAD

**Issue by senterFoward** [Outfit-of-the-Trip/OOTT-APP#7]
전날 전설님께서 자료 보내주신대로 인스타그램 기반으로 MainPage UI 수정해보았습니다.
성훈님께서 금주 금요일까지 API 완성해주시면 API연동하여 다시 push하겠습니다. 
마지막으로 UI와 UX는 계속 수정할 예정입니다.

**Comment by aest3ra** [comment]
확인 완료 후 merge 했습니다!
